# Generated by Django 6.0 on 2026-05-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='generated_thumbnails/'),
        ),
    ]
